baseURL = 'https://ismaelmartinez.github.io/ismaelmartinez.me.uk/'
title = 'IMR'
theme = 'ananke'
languageDirection = 'ltr'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[fontmatter]
    default = 'toml'

[languages]
    [languages.en]
        contentDir = 'content/en'
        languageCode = 'en-gb'
        languageName = 'English'
        weight = 1    
        [languages.en.params]
            subtitle = 'Blog and Me'
    [languages.es]
        contentDir = 'content/es'
        languageCode = 'es'
        languageName = 'Castellano'
        weight = 2
        [languages.es.params]
            subtitle = 'Blog y Yo'
    [languages.cat]
        contentDir = 'content/cat'
        languageCode = 'ca'
        languageName = 'Catala'
        weight = 3
        [languages.cat.params]
            subtitle = 'Blog i Jo'

[output]
    home = ['HTML', 'RSS', 'JSON']